/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface": "#f9f9ff",
        "surface-dim": "#d1daf4",
        "surface-bright": "#f9f9ff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f1f3ff",
        "surface-container": "#e9edff",
        "surface-container-high": "#e1e8ff",
        "surface-container-highest": "#d9e2fc",
        "on-surface": "#121b2e",
        "on-surface-variant": "#44474e",
        "inverse-surface": "#273044",
        "inverse-on-surface": "#edf0ff",
        "outline": "#75777f",
        "outline-variant": "#c5c6cf",
        "surface-tint": "#4b5e85",
        "primary": "#000b23",
        "on-primary": "#ffffff",
        "primary-container": "#0b2145",
        "on-primary-container": "#7689b3",
        "inverse-primary": "#b3c6f3",
        "secondary": "#006d39",
        "secondary-action": "#16B866",
        "secondary-hover": "#20C879",
        "on-secondary": "#ffffff",
        "secondary-container": "#71fda2",
        "on-secondary-container": "#00743d",
        "tertiary": "#000b20",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#002149",
        "on-tertiary-container": "#3188f8",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#d8e2ff",
        "primary-fixed-dim": "#b3c6f3",
        "on-primary-fixed": "#031a3e",
        "on-primary-fixed-variant": "#34466c",
        "secondary-fixed": "#71fda2",
        "secondary-fixed-dim": "#51e089",
        "on-secondary-fixed": "#00210d",
        "on-secondary-fixed-variant": "#005229",
        "tertiary-fixed": "#d6e3ff",
        "tertiary-fixed-dim": "#aac7ff",
        "on-tertiary-fixed": "#001b3e",
        "on-tertiary-fixed-variant": "#00468d",
        "background": "#f9f9ff",
        "on-background": "#121b2e",
        "surface-variant": "#d9e2fc",
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
        display: ["'Plus Jakarta Sans'", "sans-serif"],
        heading: ["'Plus Jakarta Sans'", "sans-serif"],
        "display-hero": ["'Plus Jakarta Sans'", "sans-serif"],
        "headline-xl": ["'Plus Jakarta Sans'", "sans-serif"],
        "headline-lg": ["'Plus Jakarta Sans'", "sans-serif"],
        "headline-md": ["'Plus Jakarta Sans'", "sans-serif"],
        "headline-sm": ["'Plus Jakarta Sans'", "sans-serif"],
        "body-xl": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "label-lg": ["'Plus Jakarta Sans'", "sans-serif"],
        "label-md": ["'Plus Jakarta Sans'", "sans-serif"],
        "label-sm": ["'Plus Jakarta Sans'", "sans-serif"],
        "stat-metric": ["'Plus Jakarta Sans'", "sans-serif"],
      },
      borderRadius: {
        'DEFAULT': '0.5rem',
        'md': '0.75rem',
        'lg': '1rem',
        'xl': '1.25rem',
        '2xl': '1.5rem',
        '3xl': '2rem',
        'full': '9999px',
      },
      boxShadow: {
        'level-1': '0 2px 8px -2px rgba(11, 33, 69, 0.04), 0 6px 16px -4px rgba(11, 33, 69, 0.06)',
        'level-2': '0 4px 12px -2px rgba(11, 33, 69, 0.06), 0 12px 28px -6px rgba(11, 33, 69, 0.08)',
        'level-3': '0 8px 24px -4px rgba(11, 33, 69, 0.08), 0 24px 48px -12px rgba(11, 33, 69, 0.16)',
      },
      maxWidth: {
        'content': '1440px',
      }
    },
  },
  plugins: [],
}
